# Generated by Django 4.1.7 on 2023-04-01 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogImageFragments',
            new_name='BlogImageFragment',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='user',
            new_name='author',
        ),
        migrations.AddField(
            model_name='blog',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes', to='Home.bloglike'),
        ),
        migrations.AddField(
            model_name='blogcomment',
            name='blog',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Home.blog'),
        ),
        migrations.AddField(
            model_name='blogcomment',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='comment_likes', to='Home.commentlike'),
        ),
        migrations.AddField(
            model_name='blogvideofragment',
            name='gener',
            field=models.CharField(max_length=225, null=True),
        ),
    ]
