# Generated by Django 4.1.7 on 2023-04-01 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_rename_blogimagefragments_blogimagefragment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogvideofragment',
            name='gener',
        ),
        migrations.AddField(
            model_name='blog',
            name='gener',
            field=models.CharField(max_length=225, null=True),
        ),
    ]
