# Generated by Django 4.1.7 on 2023-04-07 08:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_remove_blogvideofragment_gener_blog_gener'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogimagefragment',
            name='order',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='blogvideofragment',
            name='order',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='blogcomment',
            name='replay_for',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Home.blogcomment'),
        ),
        migrations.AlterField(
            model_name='blogimagefragment',
            name='image_link',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blogvideofragment',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='fragment_videos', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MP4'])]),
        ),
        migrations.AlterField(
            model_name='blogvideofragment',
            name='video_link',
            field=models.TextField(blank=True, null=True),
        ),
    ]
