# Generated by Django 4.1.7 on 2023-04-07 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_blogimagefragment_order_blogvideofragment_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogvideofragment',
            name='order',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='blogvideofragment',
            name='text',
            field=models.TextField(),
        ),
    ]
