# Generated by Django 4.1.7 on 2023-04-12 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_alter_blogvideofragment_order_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogcomment',
            old_name='type',
            new_name='comment_type',
        ),
    ]
